CREATE TABLE IF NOT EXISTS recommendations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  market TEXT NOT NULL,
  symbol TEXT NOT NULL,
  company_name TEXT NOT NULL,
  side TEXT NOT NULL,
  horizon TEXT NOT NULL,
  sector TEXT NOT NULL,
  pool TEXT NOT NULL,
  thesis TEXT NOT NULL,
  conviction REAL NOT NULL,
  current_price REAL NOT NULL,
  entry_low REAL,
  entry_high REAL,
  target_1 REAL,
  target_2 REAL,
  stop_loss REAL,
  rr REAL,
  leading_sector_json TEXT NOT NULL,
  transmission_event_json TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS decision_ledger (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  session TEXT NOT NULL,
  market TEXT NOT NULL,
  symbol TEXT NOT NULL,
  sector TEXT NOT NULL,
  horizon TEXT NOT NULL,
  level1_sector_score REAL,
  level1_rotation_regime TEXT,
  level2_rank_in_sector INTEGER,
  level2_sector_fit_score REAL,
  level3_execution_score REAL,
  push_decision TEXT NOT NULL,
  push_reason TEXT NOT NULL,
  reject_reason_codes TEXT NOT NULL,
  contract_version TEXT NOT NULL,
  input_artifact_hash TEXT NOT NULL,
  freshness_status TEXT,
  catalyst_status TEXT,
  entry_triggered INTEGER,
  stop_hit INTEGER,
  target_1_hit INTEGER,
  target_2_hit INTEGER,
  mfe_pct REAL,
  mae_pct REAL,
  outcome_1d REAL,
  outcome_2d REAL,
  outcome_5d REAL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
