CREATE TABLE IF NOT EXISTS recommendations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  market TEXT NOT NULL,
  symbol TEXT NOT NULL,
  company_name TEXT NOT NULL,
  side TEXT NOT NULL,
  horizon TEXT NOT NULL,
  sector TEXT NOT NULL,
  pool TEXT NOT NULL,
  thesis TEXT NOT NULL,
  conviction REAL NOT NULL,
  current_price REAL NOT NULL,
  entry_low REAL,
  entry_high REAL,
  target_1 REAL,
  target_2 REAL,
  stop_loss REAL,
  rr REAL,
  leading_sector_json TEXT NOT NULL,
  transmission_event_json TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS decision_ledger (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  session TEXT NOT NULL,
  market TEXT NOT NULL,
  symbol TEXT NOT NULL,
  sector TEXT NOT NULL,
  horizon TEXT NOT NULL,
  level1_sector_score REAL,
  level1_rotation_regime TEXT,
  level2_rank_in_sector INTEGER,
  level2_sector_fit_score REAL,
  level3_execution_score REAL,
  push_decision TEXT NOT NULL,
  push_reason TEXT NOT NULL,
  reject_reason_codes TEXT NOT NULL,
  contract_version TEXT NOT NULL,
  input_artifact_hash TEXT NOT NULL,
  freshness_status TEXT,
  catalyst_status TEXT,
  entry_triggered INTEGER,
  stop_hit INTEGER,
  target_1_hit INTEGER,
  target_2_hit INTEGER,
  mfe_pct REAL,
  mae_pct REAL,
  outcome_1d REAL,
  outcome_2d REAL,
  outcome_5d REAL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS signal_ledger (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL,
  trade_date TEXT NOT NULL,
  session TEXT NOT NULL,
  signal_key TEXT NOT NULL,
  market TEXT NOT NULL,
  symbol TEXT NOT NULL,
  company_name TEXT,
  sector TEXT,
  playbook TEXT NOT NULL,
  side TEXT NOT NULL,
  push_price REAL NOT NULL,
  push_score REAL,
  three_locks_status TEXT,
  three_locks_score REAL,
  support_level REAL,
  pressure_level REAL,
  reason TEXT,
  source_payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(trade_date, session, market, symbol, playbook)
);

CREATE TABLE IF NOT EXISTS signal_outcomes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  signal_id INTEGER NOT NULL,
  review_date TEXT NOT NULL,
  current_price REAL,
  raw_return_pct REAL,
  trade_return_pct REAL,
  max_price_since_push REAL,
  min_price_since_push REAL,
  max_gain_pct REAL,
  max_drawdown_pct REAL,
  days_since_signal INTEGER,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(signal_id, review_date),
  FOREIGN KEY(signal_id) REFERENCES signal_ledger(id)
);
